### PR TITLE
Add client and server specification drafts

### PR DESCRIPTION
**Pull request by davidjrichardson**
This branch outlines the how the new version of dcs-get should work, both on the client and on the server level. Any changes should be discussed here, as well as any questions asked.

### CODE REVIEW

**Comment by Veltas** [comment]
GET /dcs-get

Might want to replace that with `GET /`, would look a little weird as a URL, presumably will be like `http://repackaged.uwcs.co.uk/dcs-get` when it may as well be `http://repackaged.uwcs.co.uk/`

**Comment by davidjrichardson** [comment]
Fair point - I was assuming it'd still end up on `backus.uwcs.co.uk`. This is something to think about I suppose.

**Comment by Veltas** [comment]
Missing the opportunity to re-evaluate the type. The type seems to be used to specify different properties of packages that are not mutually exclusive. Types in circulation are nil, "dev", "game", "meta" if I remember rightly. In my opinion Types should be a set:

    {
        packages: [
            {
                name: String,
                description: String,
                versions: [ String, ... ],
                types: { ... }
            },
            ...
        ]
    }

Not sure if that's valid JSON, maybe:

    {
        packages: [
            {
                name: String,
                description: String,
                versions: [ String, ... ],
                types: [ ... ]
            },
            ...
        ]
    }

dev is not a 'default' type at the moment

**Comment by davidjrichardson** [comment]
@Veltas What would you consider a "default" type then, there was one? I am aware that gaming-get uses "game", but what uses "meta" and "dev"?

**Comment by Veltas** [comment]
@davidjrichardson :
> Fair point - I was assuming it'd still end up on `backus.uwcs.co.uk`. This is something to think about I suppose.

I think we should put it somewhere else. This might replace dcs-get eventually, but for the time being dcs-get will need to operate along-side this. Certainly while it's in development, but also things like gaming-get will need to be rewritten for the new system. May as well give it a new name and URL IMO.

**Comment by Veltas** [comment]
@davidjrichardson :
> What would you consider a "default" type then, there was one? I am aware that gaming-get uses "game", but what uses "meta" and "dev"?

The meta type is used for packages that do not have any files associated with them. An example is clang, which is listed as a meta package, with llvm as a dependency (clang comes with llvm).

**Comment by davidjrichardson** [comment]
These types should probably be formalised in the specification, then.

**Comment by Veltas** [comment]
I don't think you need to formalise the types in this specification (they should be mentioned somewhere, implementations will need to work around the possibility that other types will be added in future).

The types are properties of a package. Games should have a "game" type so we know to list them on gaming-get, meta packages should have the "meta" type so we know not to try and download packages for them.

**Comment by davidjrichardson** [comment]
The initial spec for the client application is now available

**Comment by davidjrichardson** [comment]
With no further comments being made about the specification(s), I'll merge this and start working on an implementation.

**Pull request merged**
